import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="591713391589-m9npu4dbsnie5lp9vcdaa2rtmj83jpiq.apps.googleusercontent.com">
        <body className={inter.className}>{children}</body>
        
      </GoogleOAuthProvider>
    </html>
  );
}
